// Runs at Vercel build time.
// Reads env vars → writes js/firebase-config.js so the browser can import it.
const fs = require('fs');

const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_DATABASE_URL',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
];

const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error('Missing Vercel env vars:', missing.join(', '));
  process.exit(1);
}

const content = `// Auto-generated by build.js — do not edit manually.
export const FIREBASE_CONFIG = {
  apiKey:            "${process.env.FIREBASE_API_KEY}",
  authDomain:        "${process.env.FIREBASE_AUTH_DOMAIN}",
  databaseURL:       "${process.env.FIREBASE_DATABASE_URL}",
  projectId:         "${process.env.FIREBASE_PROJECT_ID}",
  storageBucket:     "${process.env.FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
  appId:             "${process.env.FIREBASE_APP_ID}",
};
`;

fs.writeFileSync('js/firebase-config.js', content);
console.log('✓ js/firebase-config.js generated from env vars.');
